### ISSUE TITLE
Always return empty string

### ISSUE THREAD

**Issue by StyleShit** [shutterstock/api-php-client#2]
I tried this code:

    $sapi = new ShutterstockApiClient();

    $search_result = $sapi->search('dog');
    
    var_dump( $search_result );

But it always return an empty string and "Error while getting Access Token".

 What can I do?

(I put Consumer Key as $auth_username and Consumer Secret as $auth_key, is it OK?)

**Comment by PSchwisow** [comment]
I'm sorry about the confusion. This example code points to an outdated version of our API. I would recommend instead looking at https://github.com/shutterstock/php-shutterstock-api.

I will mark this repository as deprecated to avoid further confusion.
